/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth_admin)'}/Adminlogin` | `/Adminlogin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth_chair)'}/ProgChairlogin` | `/ProgChairlogin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth_instructor)'}/Instructorlogin` | `/Instructorlogin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs_admin)'}/Amenu` | `/Amenu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs_admin)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs_admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs_admin)'}/Progmenu` | `/Progmenu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs_instructor)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth_admin)'}/Adminlogin` | `/Adminlogin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth_chair)'}/ProgChairlogin` | `/ProgChairlogin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth_instructor)'}/Instructorlogin` | `/Instructorlogin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs_admin)'}/Amenu` | `/Amenu`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs_admin)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs_admin)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs_admin)'}/Progmenu` | `/Progmenu`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs_instructor)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth_admin)'}/Adminlogin${`?${string}` | `#${string}` | ''}` | `/Adminlogin${`?${string}` | `#${string}` | ''}` | `${'/(auth_chair)'}/ProgChairlogin${`?${string}` | `#${string}` | ''}` | `/ProgChairlogin${`?${string}` | `#${string}` | ''}` | `${'/(auth_instructor)'}/Instructorlogin${`?${string}` | `#${string}` | ''}` | `/Instructorlogin${`?${string}` | `#${string}` | ''}` | `${'/(tabs_admin)'}/Amenu${`?${string}` | `#${string}` | ''}` | `/Amenu${`?${string}` | `#${string}` | ''}` | `${'/(tabs_admin)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs_admin)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs_admin)'}/Progmenu${`?${string}` | `#${string}` | ''}` | `/Progmenu${`?${string}` | `#${string}` | ''}` | `${'/(tabs_instructor)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth_admin)'}/Adminlogin` | `/Adminlogin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth_chair)'}/ProgChairlogin` | `/ProgChairlogin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth_instructor)'}/Instructorlogin` | `/Instructorlogin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs_admin)'}/Amenu` | `/Amenu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs_admin)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs_admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs_admin)'}/Progmenu` | `/Progmenu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs_instructor)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
